[package]
name = "embre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
embre-crypt = { path = "crypt"}
embre-macro = { path = "macro"}
widestring = "1.0.2"

[workspace]
members = [
    "_test",
    "build",
    "core",
    "crypt",
    "macro",
]
