[package]
name = "embre-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
embre-core = { path = "../core" }

[features]
default = []
aes = ["embre-core/aes"]
openssl = ["embre-core/openssl"]
openssl-vendored = ["embre-core/openssl", "embre-core/openssl-vendored"]